# Generated by Django 5.2.3 on 2025-06-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BackgroundJobLock",
        ),
    ]
