# Generated by Django 5.2.3 on 2025-06-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_delete_backgroundjoblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfdocument",
            name="is_downloaded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="local_path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
