# Generated by Django 5.2.3 on 2025-06-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_pdfdocument_is_downloaded_pdfdocument_local_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfdocument",
            name="is_parsed",
            field=models.BooleanField(default=False),
        ),
    ]
